### ISSUE TITLE
Google Maps API Key

### ISSUE THREAD

**Issue by JadeP27** [jonnahmarie/Project-1-Basix#2]
How do we get an API key?
What are the limitations?
What do we request?
What are the responses?

**Comment by vtaymany** [comment]
How do we get an API key?
We must register a credit card to get access to a key. Upon registration, we will receive an instant $300 credit and then $200/mo free credit which means if our usage is under $200/mo we'll be a free user.
[https://developers.google.com/maps/billing-credits](https://developers.google.com/maps/billing-credits)

What are the limitations?
Different Google Maps API calls have different pricing, we just need to stay under $200/mo.

What do we request?
For Autocomplete: [https://developers.google.com/maps/documentation/javascript/examples/places-autocomplete-addressform](https://developers.google.com/maps/documentation/javascript/examples/places-autocomplete-addressform)

What are the responses?
No response for the autocomplete, the user will be shown a dropdown menu of suggestions. Once the user clicks on a suggestion the form will complete and we can treat the input as a normal text field input.

**Comment by vtaymany** [comment]
From group meeting on 11/14/2020:

It would be better if we could omit this API altogether.

The user just needs to input their ZIP.
